### Problem Set 1-- Numpy Part

#### Name: Zunda Xu (zunda@uchicago.edu)

#### Problem 1

In [2]:
# Import the library 
import numpy as np

In [8]:
def array_multiple():
    A = np.array( [ [3, 1, -4],[1, 5, -9] ] )
    B = np.array( [ [2, 6, -5, 3],[5, -8, 9, 7], [9, -3, -2, -3] ] )
    inner_product = np.dot(A, B)
    return inner_product

In [9]:
inner_product = array_multiple()

In [11]:
print("The matrix product AB is:", inner_product)

The matrix product AB is: [[-25  22   2  28]
 [-54  -7  58  65]]


#### Problem 2

In [12]:
def matrix_function():
    A = np.array( [ [3, 1, 4],[1, 5, 9], [-5, 3, 1] ] )
    F = -(A @ A @ A) + 9 * (A @ A) - 15 * A
    return F

In [14]:
F = matrix_function()
print("The answer to problem  2 is:", F)

The answer to problem set 2 is: [[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Problem 3

In [12]:
def matrix_product():
    A = np.triu(np.ones((7,7), dtype=np.int))
    B = np.full_like(A, -1)
    index = np.triu_indices(7,1)
    B[index] = 5
    product = A @ B @ A
    return product.astype(np.int64)

In [13]:
ABA = matrix_product()
print("The answer of problem 3 is:", ABA)

The answer of problem 3 is: [[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


#### Problem 4

In [14]:
def fancy_index(A):
    array_1 = A.copy()
    mask = array_1 < 0 
    array_1[mask] = 0
    return array_1

In [15]:
A = np.array([1,0,0,-1,-2,0,4,-3])
array_1 = fancy_index(A)
print(array_1)

[1 0 0 0 0 0 4 0]


#### Problem 5

In [29]:
def stack():
    A = np.arange(6).reshape((2,3))
    B = np.tril(np.ones((3,3))) *3
    C = np.eye(3)*3
    z1 = np.zeros((3,3))
    z2 = np.zeros((5,2))
    z3 = np.zeros((2,3))
    I = np.eye(3)
    col1 = np.vstack((z1,A,B))
    col2 = np.vstack((A.T,z2))
    col3 = np.vstack((I,z3,C))
    matrix = np.hstack((col1,col2,col3))
    return matrix

In [30]:
matrix = stack()
print("The answer of problem 5 is:", matrix)

The answer of problem 5 is: [[ 0.  0.  0.  0.  3.  1.  0.  0.]
 [ 0.  0.  0.  1.  4.  0.  1.  0.]
 [ 0.  0.  0.  2.  5.  0.  0.  1.]
 [ 0.  1.  2.  0.  0.  0.  0.  0.]
 [ 3.  4.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  3.  0.  0.]
 [ 3.  3.  0.  0.  0.  0.  3.  0.]
 [ 3.  3.  3.  0.  0.  0.  0.  3.]]


#### Problem 6

In [31]:
def row_stochastics(A):
    row_sum = A.sum(axis = 1)
    new_matrix = A/ row_sum[:, np.newaxis]
    return new_matrix

In [40]:
new_matrix = row_stochastics(np.array([[1,3],[2,5]]))
print("The answer of problem 6 is:", new_matrix)

The answer of problem 6 is: [[ 0.25        0.75      ]
 [ 0.28571429  0.71428571]]


#### Problem 7

In [49]:
grid = np.load("grid.npy")

In [54]:
def four_max():
    h_max = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    v_max = np.max(grid[:-3, :]* grid[1:-2, :] * grid[2:-1, :] * grid[3:, :])
    r_max = np.max(grid[:-3, :-3]* grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    l_max = np.max(grid[:-3, 3:]* grid[1:-2, 2:-1] * grid[2:-1, 1:-2] * grid[3:, :-3])
    return max(h_max, v_max, r_max, l_max)

In [55]:
max_product = four_max()
print("The answer of problem 7 is:", max_product)

The answer of problem 7 is: 70600674


###  Problem Set 1-- Standard Library Part

#### Problem 1

In [171]:
def list_statistics(l):
    print(min(l), max(l), sum(l)/len(l))

In [172]:
list_statistics([4,9,13,2,3])

2 13 6.2


#### Problem 2

In [174]:
A = 1
new_A = A
new_A = 2
print(new_A == A)
B = "A"
new_B = B
new_B = "B"
print(new_B == B)

C = [1,2,3]
new_C = C
new_C[2] = 4
print(new_C == C)

D = (1,3)
new_D = D
new_D = (3,1)
print(new_D == D)

E = set([1,2])
new_E = E
new_E = set([2,2])
print(new_E == E)

False
False
True
False
False


#### Problem 3

In [175]:
import math
def calculator_sum(a,b):
    return a+b
def calculator_hyp(a,b):
    return math.sqrt(calculator_sum(a*a, b*b))

In [176]:
calculator_hyp(3,4)

5.0

#### Problem 4

In [179]:
def power_set(A):
    lenth = len(A)
    for i in range(1 << lenth):
        print([A[j] for j in range(lenth) if (i & (1 << j))])

In [180]:
power_set([1,2,3,4])

[]
[1]
[2]
[1, 2]
[3]
[1, 3]
[2, 3]
[1, 2, 3]
[4]
[1, 4]
[2, 4]
[1, 2, 4]
[3, 4]
[1, 3, 4]
[2, 3, 4]
[1, 2, 3, 4]


###  Problem Set 1-- Unit Testing

###  Problem Set 1-- Object Oriented Programming

#### Problem 1

In [181]:
class Backpack:
    def __init__(self, name, color, max_size = 5): # This function is the constructor.
        '''
        Set the name and initialize an empty list of contents.
        Parameters:
        name (str): the name of the backpack's owner.
        '''
        self.name = name # Initialize some attributes.
        self.contents = []
        self.color = color
        self.max_size = max_size

    def put(self, item):
        '''
        Add 'item' to the backpack's list of contents.
        '''
        if len(self.contents) > self.max_size:
            print("Overcapacity")
        else:
            self.contents.append(item) # Use 'self.contents', not just 'contents'.
            
    def take(self, item):
        '''
        Remove 'item' from the backpack's list of contents.
        '''
        self.contents.remove(item)
        
    def dump(self): # remove contents
        self.contents = []

In [182]:
def test_backpack(name):
    testpack = Backpack(name, "black") # Instantiate the object.
    if testpack.name != "Barry": # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item) # Test a method.
    print("Contents:", testpack.contents)

In [183]:
test_backpack("Barry")

Contents: ['pencil', 'pen', 'paper', 'computer']


In [184]:
test_backpack("no")

Backpack.name assigned incorrectly
Contents: ['pencil', 'pen', 'paper', 'computer']


#### Problem 2

In [185]:
class Jetpack(Backpack):
    # this is a jetpack which is a backpack but with fuel
    def __init__(self, name, color, max_size=2, fuel=10):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
        
    def fly(self, fuel_burned): # bunrs the fuel
        self.fuel = self.fuel - fuel_burned 
        
    def dump(self): # dumps everything including fuel
        Backpack.dump(self)
        self.fuel = 0

In [190]:
jetpack = Jetpack("Ari", "blue")

In [191]:
jetpack.fly(4)
jetpack.fuel

6

In [192]:
jetpack.dump()

In [193]:
jetpack.fuel

0

#### Problem 3

In [198]:
class Backpack(object):
    
    def __init__(self, name, color, max_size = 5): # This function is the constructor.
        '''
        Set the name and initialize an empty list of contents.
        Parameters:
        name (str): the name of the backpack's owner.
        '''
        self.name = name # Initialize some attributes.
        self.contents = []
        self.color = color
        self.max_size = max_size

    def put(self, item):
        '''
        Add 'item' to the backpack's list of contents.
        '''
        if len(self.contents) > self.max_size:
            print("Overcapacity")
        else:
            self.contents.append(item) # Use 'self.contents', not just 'contents'.
            
    def take(self, item):
        '''
        Remove 'item' from the backpack's list of contents.
        '''
        self.contents.remove(item)
        
    def dump(self): # remove contents
        self.contents = []
        
    def __eq__(self, other): # is it the same
        if (self.name == other.name) & (self.color == other.color) & (len(self.contents) == len(other.contents)):
            return True
        
    def __str__():
        return '''Owner:\t\t{}
        \nColor:\t\t{} 
        \nSize:\t\t{}
        \nMax Size:\t{}
        \nContents:\t{}'''.format(self.name,self.color,len(self.contents),
                                  self.max_size, self.contents)

#### Problem 4

In [195]:
class ComplexNumber(object):
    
    def __init__(self, a ,b):
        self.real = a
        self.imag = b
    
    def conjugate(self):
        b = -self.imag
        return ComplexNumber(self.real, b)
    
    def __str__(self):
        return("("+str(self.real) + "" + str(self.imag) + "j)")
    
    def __abs__(self):
        return math.sqrt(self.real ** 2 + self.imag ** 2)
    
    def __eq__(self, other):
        return (self.real == other.real) and (self.imag == other.imag)
    
    def __add__(self, other):
        real = self.real + other.real
        imag = self.imag + other.imag
        return ComplexNumber(real, imag)

    def __sub__(self, other):
        real = self.real - other.real
        imag = self.imag - other.imag
        return ComplexNumber(real, imag)

    def __mul__(self, other):
        real = self.real*other.real - self.imag*other.imag
        imag = self.imag*other.real + other.imag*self.real
        return ComplexNumber(real, imag)
        
    def __truediv__(self, other):
            t = self*other.conjugate()
            b = (other*other.conjugate()).real
            res = ComplexNumber(t.real / b, t.imag/b)
            return res

In [196]:
def test_ComplexNumber(a, b):
    py_cnum, my_cnum = complex(a, b), ComplexNumber(a, b)
    # Validate the constructor.
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    # Validate conjugate() by checking the new number's imag attribute.
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print("__str__() failed for", py_cnum)
        if str(py_cnum) != str(my_cnum):
            print("__str__() failed for", py_cnum)
    print(my_cnum-my_cnum)
    print(my_cnum*my_cnum)
    print(my_cnum-my_cnum)
    print(abs(my_cnum))
    print(my_cnum==py_cnum)

In [197]:
test_ComplexNumber(4,-6)

(00j)
(-20-48j)
(00j)
7.211102550927978
True


###  Problem Set 1-- Exceptions and File I/O

#### Problem 1

In [62]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                           "digits differ by 2 or more: ")
    if len(step_1) != 3:
        raise ValueError("The first number is not a 3-digit number.")
    if abs(int(step_1[2])-int(step_1[0])) < 2:
        raise ValueError("The first number’s first and last digits differ by less than 2.")
    step_2 = input("Enter the reverse of the first number, obtained "
                                              "by reading it backwards: ")
    if int(step_2[2]) != int(step_1[0]) or int(step_2[0]) != int(step_1[2]) or int(step_2[1]) != int(step_1[1]):
        raise ValueError("The second number is not the reverse of the first number.")
    step_3 = input("Enter the positive difference of these numbers: ")
    if int(step_3) != abs(int(step_1)-int(step_2)):
        raise ValueError("The third number is not the positive difference of the first two numbers.")
    step_4 = input("Enter the reverse of the previous result: ")
    if int(step_4[2]) != int(step_3[0]) or int(step_4[0]) != int(step_3[2]) or int(step_4[1]) != int(step_3[1]):
        raise ValueError("The fourth number is not the reverse of the third number.")
    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")

In [63]:
arithmagic()

Enter a 3-digit number where the first and last digits differ by 2 or more: 124
Enter the reverse of the first number, obtained by reading it backwards: 421
Enter the positive difference of these numbers: 297
Enter the reverse of the previous result: 792
297 + 792 = 1089 (ta-da!)


#### Problem 2

In [16]:
from random import choice

def random_walk(max_iters=1e12):
    walk = 0
    directions = [1, -1]
    try:
        for i in range(int(max_iters)):
            walk += choice(directions)
    except KeyboardInterrupt:
        print("Process interrupted at iteration {}".format(i))
    else:
        print("Process completed")
    finally:
        return(walk)

In [17]:
print(random_walk())

Process interrupted at iteration 2817140
-630


#### Problem 3

In [162]:
class ContentFilter(object):
    def __init__(self, filename):
        self.filename = filename
        try:
            with open(self.filename,"r") as myfile:
                self.contents = myfile.read().split('\n')
        except FileNotFoundError:
            filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except TypeError:
            filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except OSError:
            filename = str(input("Please enter a valid file name:"))
            ContentFilter(filename)

In [166]:
cf1 = ContentFilter("cf_example.txt")

Please enter a valid file name:cf_example1.txt


#### Problem 4

In [90]:
class ContentFilter(object):
    def __init__(self, filename):
        self.filename = filename
        try:
            with open(self.filename,"r") as myfile:
                self.contents = myfile.read().split('\n')
        except FileNotFoundError:
            filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except TypeError:
            self.filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except OSError:
            self.filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        self.total = 0
        self.alpha = 0
        self.digit = 0
        self.whitespace = 0
        self.line = len(self.contents)
        for i in range(self.line):
            for j in range(len(self.contents[i])):
                self.total += 1
                if self.contents[i][j].isspace():
                    self.whitespace += 1
                if self.contents[i][j].isdigit():
                    self.digit += 1
                if self.contents[i][j].isalpha():
                    self.alpha += 1
            
            
    def uniform(self, new_filename, mode='w', case="upper"):
        if mode not in ['w','x','a']:
            raise ValueError("Mode is not 'w', 'x', or 'a'")
        if case not in ['upper','lower']:
            raise ValueError("Case is not 'upper' or 'lower'")
        with open(new_filename, mode) as newfile:
            for i in range(len(self.contents)):
                if case == "upper":
                    newfile.write(self.contents[i].upper() + "\n")
                elif case == "lower":
                    newfile.write(self.contents[i].lower() + "\n")
                    
    def reverse(self, new_filename, mode='w', unit ="line"):
        if mode not in ['w','x','a']:
            raise ValueError("Mode is not 'w', 'x', or 'a'")
        if unit not in ['line','word']:
            raise ValueError("Case is not 'line' or 'unit'")
        with open(new_filename, mode) as newfile:
                if unit == "word":
                    for i in range(len(self.contents)):
                        newfile.write(self.contents[i][::-1] + "\n")
                elif unit == "line":
                    for i in range(len(self.contents)):
                        newfile.write(self.contents[::-1][i] + "\n")
                        
    def transpose(self, new_filename, mode='w'):
        if mode not in ['w','x','a']:
            raise ValueError("Mode is not 'w', 'x', or 'a'")
        with open(new_filename, mode) as newfile:
            for i in range(len(self.contents[0].split())):
                new_line = []
                for j in range(len(self.contents)):
                    content = self.contents[j].split()
                    new_line.append(content[i])
                newfile.write(" ".join(new_line) + "\n")
    def __str__(self):
        return "Source file: {}".format(self.filename) + "\n" + "Total characters: {}".format(self.total) + "\n" + "Alphabetic characters: {}".format(self.alpha) \
                + "\n" + "Numerical characters: {}".format(self.digit) + "\n" + "Whitespace characters: {}".format(self.whitespace) + "\n" + "Number of lines: {}".format(self.line)

In [91]:
cf = ContentFilter("cf_example1.txt")

In [83]:
cf.uniform("uniform.txt", mode='w', case="upper")

In [84]:
cf.uniform("uniform.txt", mode='a', case="lower")

In [85]:
cf.reverse("reverse.txt", mode='w', unit="word")

In [86]:
cf.reverse("reverse.txt", mode='a', unit="line")

In [92]:
cf.transpose("transpose.txt", mode='w')

In [94]:
print(cf)

Source file: cf_example1.txt
Total characters: 10
Alphabetic characters: 6
Numerical characters: 0
Whitespace characters: 4
Number of lines: 2
