### Problem Set 1-- Numpy Part

#### Name: Zunda Xu (zunda@uchicago.edu)

#### Problem 1

In [2]:
# Import the library 
import numpy as np

In [8]:
def array_multiple():
    A = np.array( [ [3, 1, -4],[1, 5, -9] ] )
    B = np.array( [ [2, 6, -5, 3],[5, -8, 9, 7], [9, -3, -2, -3] ] )
    inner_product = np.dot(A, B)
    return inner_product

In [9]:
inner_product = array_multiple()

In [11]:
print("The matrix product AB is:", inner_product)

The matrix product AB is: [[-25  22   2  28]
 [-54  -7  58  65]]


#### Problem 2

In [12]:
def matrix_function():
    A = np.array( [ [3, 1, 4],[1, 5, 9], [-5, 3, 1] ] )
    F = -(A @ A @ A) + 9 * (A @ A) - 15 * A
    return F

In [14]:
F = matrix_function()
print("The answer to problem  2 is:", F)

The answer to problem set 2 is: [[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Problem 3

In [12]:
def matrix_product():
    A = np.triu(np.ones((7,7), dtype=np.int))
    B = np.full_like(A, -1)
    index = np.triu_indices(7,1)
    B[index] = 5
    product = A @ B @ A
    return product.astype(np.int64)

In [13]:
ABA = matrix_product()
print("The answer of problem 3 is:", ABA)

The answer of problem 3 is: [[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


#### Problem 4

In [14]:
def fancy_index(A):
    array_1 = A.copy()
    mask = array_1 < 0 
    array_1[mask] = 0
    return array_1

In [15]:
A = np.array([1,0,0,-1,-2,0,4,-3])
array_1 = fancy_index(A)
print(array_1)

[1 0 0 0 0 0 4 0]


#### Problem 5

In [29]:
def stack():
    A = np.arange(6).reshape((2,3))
    B = np.tril(np.ones((3,3))) *3
    C = np.eye(3)*3
    z1 = np.zeros((3,3))
    z2 = np.zeros((5,2))
    z3 = np.zeros((2,3))
    I = np.eye(3)
    col1 = np.vstack((z1,A,B))
    col2 = np.vstack((A.T,z2))
    col3 = np.vstack((I,z3,C))
    matrix = np.hstack((col1,col2,col3))
    return matrix

In [30]:
matrix = stack()
print("The answer of problem 5 is:", matrix)

The answer of problem 5 is: [[ 0.  0.  0.  0.  3.  1.  0.  0.]
 [ 0.  0.  0.  1.  4.  0.  1.  0.]
 [ 0.  0.  0.  2.  5.  0.  0.  1.]
 [ 0.  1.  2.  0.  0.  0.  0.  0.]
 [ 3.  4.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  3.  0.  0.]
 [ 3.  3.  0.  0.  0.  0.  3.  0.]
 [ 3.  3.  3.  0.  0.  0.  0.  3.]]


#### Problem 6

In [31]:
def row_stochastics(A):
    row_sum = A.sum(axis = 1)
    new_matrix = A/ row_sum[:, np.newaxis]
    return new_matrix

In [40]:
new_matrix = row_stochastics(np.array([[1,3],[2,5]]))
print("The answer of problem 6 is:", new_matrix)

The answer of problem 6 is: [[ 0.25        0.75      ]
 [ 0.28571429  0.71428571]]


#### Problem 7

In [49]:
grid = np.load("grid.npy")

In [54]:
def four_max():
    h_max = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    v_max = np.max(grid[:-3, :]* grid[1:-2, :] * grid[2:-1, :] * grid[3:, :])
    r_max = np.max(grid[:-3, :-3]* grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    l_max = np.max(grid[:-3, 3:]* grid[1:-2, 2:-1] * grid[2:-1, 1:-2] * grid[3:, :-3])
    return max(h_max, v_max, r_max, l_max)

In [55]:
max_product = four_max()
print("The answer of problem 7 is:", max_product)

The answer of problem 7 is: 70600674


###  Problem Set 1-- Standard Library Part

###  Problem Set 1-- Unit Testing

###  Problem Set 1-- Object Oriented Programming

###  Problem Set 1-- Exceptions and File I/O

#### Problem 1

In [62]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                           "digits differ by 2 or more: ")
    if len(step_1) != 3:
        raise ValueError("The first number is not a 3-digit number.")
    if abs(int(step_1[2])-int(step_1[0])) < 2:
        raise ValueError("The first number’s first and last digits differ by less than 2.")
    step_2 = input("Enter the reverse of the first number, obtained "
                                              "by reading it backwards: ")
    if int(step_2[2]) != int(step_1[0]) or int(step_2[0]) != int(step_1[2]) or int(step_2[1]) != int(step_1[1]):
        raise ValueError("The second number is not the reverse of the first number.")
    step_3 = input("Enter the positive difference of these numbers: ")
    if int(step_3) != abs(int(step_1)-int(step_2)):
        raise ValueError("The third number is not the positive difference of the first two numbers.")
    step_4 = input("Enter the reverse of the previous result: ")
    if int(step_4[2]) != int(step_3[0]) or int(step_4[0]) != int(step_3[2]) or int(step_4[1]) != int(step_3[1]):
        raise ValueError("The fourth number is not the reverse of the third number.")
    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")

In [63]:
arithmagic()

Enter a 3-digit number where the first and last digits differ by 2 or more: 124
Enter the reverse of the first number, obtained by reading it backwards: 421
Enter the positive difference of these numbers: 297
Enter the reverse of the previous result: 792
297 + 792 = 1089 (ta-da!)
